version: '3.6'

services:
  todo-db:
    image: postgres:16
    container_name: todo-db
    restart: always
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=tododbuser
      - POSTGRES_PASSWORD=tododbpassword
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - "5050:80"
    depends_on:
      - todo-db

volumes:
  todo-db-data:
